#!/bin/bash
# SPDX-FileCopyrightText: 2026 Gary Frattarola
# SPDX-License-Identifier: MIT OR Apache-2.0
#
# Assembles a single, self-contained managed-tier installer and writes it to
# the user's home directory as install_claude_writing_style.sh. The directive,
# digest, and lint are embedded inline (human-readable, so the sudo script can
# be inspected before running). The emitted installer writes root-owned policy
# files to the OS managed directory and then deletes itself.
#
# Usage: build-managed-installer.sh <staging-dir> [style-name] [output-path]
#   <staging-dir>  must contain: canonical.md, digest.sh, lint.py
#   [style-name]   default: "Writing Style"
#   [output-path]  default: $HOME/install_claude_writing_style.sh
set -euo pipefail

STAGING="${1:?Usage: build-managed-installer.sh <staging-dir> [style-name] [output-path]}"
STYLE_NAME="${2:-Writing Style}"
OUTPUT="${3:-${HOME}/install_claude_writing_style.sh}"
SLUG=$(printf '%s' "$STYLE_NAME" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9' '-' | sed 's/^-//;s/-$//')

for f in canonical.md digest.sh lint.py; do
    [[ -f "${STAGING}/${f}" ]] || { echo "Missing ${STAGING}/${f}" >&2; exit 1; }
done

# Collision guard: a payload must not contain the heredoc sentinel that will
# wrap it, or the emitted installer would terminate the block early.
guard() { grep -qF "$2" "$1" && { echo "Payload $1 contains sentinel $2; aborting." >&2; exit 1; } || true; }
guard "${STAGING}/canonical.md" "__CS_DIRECTIVE_EOF__"
guard "${STAGING}/canonical.md" "__CS_STYLE_EOF__"
guard "${STAGING}/digest.sh"    "__CS_DIGEST_EOF__"
guard "${STAGING}/lint.py"      "__CS_LINT_EOF__"

{
    cat <<'HDR'
#!/bin/bash
# Self-contained managed-tier installer for a Claude writing-style policy.
# Generated by claude-style-toolkit. Run once, then it deletes itself:
#     sudo ~/install_claude_writing_style.sh
# Root-owned policy is written to the OS managed directory. Safe to read first.
set -euo pipefail
if [[ $EUID -ne 0 ]]; then echo "Run with sudo: sudo \"$0\"" >&2; exit 1; fi
TARGET_USER="${SUDO_USER:?Run via sudo from your normal account, not a root shell}"
HDR
    printf 'STYLE_NAME=%q\nSLUG=%q\n' "$STYLE_NAME" "$SLUG"
    cat <<'BODY1'
case "$(uname -s)" in
    Darwin) MANAGED_DIR="/Library/Application Support/ClaudeCode"; GROUP="wheel"
            USER_HOME=$(dscl . -read "/Users/${TARGET_USER}" NFSHomeDirectory | awk '{print $2}') ;;
    Linux)  MANAGED_DIR="/etc/claude-code"; GROUP="root"
            USER_HOME=$(getent passwd "$TARGET_USER" | cut -d: -f6) ;;
    *) echo "Unsupported OS: $(uname -s)" >&2; exit 1 ;;
esac
HOOKS_DIR="${MANAGED_DIR}/hooks"
STYLE_DIR="${MANAGED_DIR}/.claude/output-styles"
mkdir -p "$HOOKS_DIR" "$STYLE_DIR"
BODY1
    # Managed CLAUDE.md (directive verbatim).
    printf 'cat > "${MANAGED_DIR}/CLAUDE.md" <<'\''__CS_DIRECTIVE_EOF__'\''\n'
    cat "${STAGING}/canonical.md"
    printf '\n__CS_DIRECTIVE_EOF__\n'
    # Output style: frontmatter + directive body.
    printf 'cat > "${STYLE_DIR}/${SLUG}.md" <<'\''__CS_STYLE_EOF__'\''\n'
    printf -- '---\nname: %s\ndescription: Writing style directive (managed; do not edit)\n---\n\n' "$STYLE_NAME"
    cat "${STAGING}/canonical.md"
    printf '\n__CS_STYLE_EOF__\n'
    # Digest hook.
    printf 'cat > "${HOOKS_DIR}/style-digest.sh" <<'\''__CS_DIGEST_EOF__'\''\n'
    cat "${STAGING}/digest.sh"
    printf '\n__CS_DIGEST_EOF__\n'
    # Lint hook.
    printf 'cat > "${HOOKS_DIR}/style-lint.py" <<'\''__CS_LINT_EOF__'\''\n'
    cat "${STAGING}/lint.py"
    printf '\n__CS_LINT_EOF__\n'
    cat <<'BODY2'
chmod 0755 "${HOOKS_DIR}/style-digest.sh" "${HOOKS_DIR}/style-lint.py"

MS="${MANAGED_DIR}/managed-settings.json"
if [[ -f "$MS" ]]; then
    cp "$MS" "${MS}.bak.$(date +%Y%m%d%H%M%S)"
    echo "Backed up existing managed-settings.json"
fi
cat > "$MS" <<JSON
{
  "outputStyle": "${STYLE_NAME}",
  "hooks": {
    "UserPromptSubmit": [ { "hooks": [ { "type": "command", "command": "\"${HOOKS_DIR}/style-digest.sh\"" } ] } ],
    "Stop": [ { "hooks": [ { "type": "command", "command": "\"${HOOKS_DIR}/style-lint.py\"" } ] } ]
  }
}
JSON

# Root-own the whole tree, then set file modes.
chown -R "root:${GROUP}" "$MANAGED_DIR"
chmod 0644 "${MANAGED_DIR}/CLAUDE.md" "$MS" "${STYLE_DIR}/${SLUG}.md"

echo "Installed (managed tier) to ${MANAGED_DIR} for style: ${STYLE_NAME}"
echo "Start a fresh Claude Code session, then verify:"
echo "  1. Ask Claude whether a managed CLAUDE.md and the '${STYLE_NAME}'"
echo "     output style are active (it can confirm both from its context)."
echo "  2. Confirm the digest line arrives with each prompt."
echo "  3. Request output violating a banned rule; the lint should block it."

SELF="${USER_HOME}/install_claude_writing_style.sh"
if [[ -f "$SELF" ]]; then
    rm -f "$SELF" && echo "Removed installer: $SELF"
fi
BODY2
} > "$OUTPUT"
chmod 0755 "$OUTPUT"

echo "Wrote self-contained installer: $OUTPUT"
echo "Have the user run, in a terminal:  sudo \"$OUTPUT\""
echo "It writes the policy root-owned and deletes itself on success."
