#!/bin/bash
# SPDX-FileCopyrightText: 2026 Gary Frattarola
# SPDX-License-Identifier: MIT OR Apache-2.0
#
# Assembles a self-contained managed-tier uninstaller and writes it to the
# user's home directory as uninstall_claude_writing_style.sh. The harness
# cannot elevate, so the user runs it: sudo ~/uninstall_claude_writing_style.sh
# The emitted uninstaller performs the settings surgery FIRST (removing only
# our entries: hooks whose command names style-digest.sh or
# style-emoji-check.sh, the review hook by its "[writing-style-policy]"
# marker, and outputStyle if it names this style or another style the
# toolkit generated), then removes our files, then removes the managed
# directory only if empty, and deletes itself.
#
# The managed CLAUDE.md is removed only when it is the toolkit's own (it
# matches the sidecar record .edgar-style-policy or a canonical in the style
# library); otherwise it is left in place, with the reason printed. A
# CLAUDE.md.pre-edgar-style-policy kept by the installer is restored.
#
# The surgery runs on whichever JSON engine the target machine has (python3,
# osascript on macOS, or node — via the inlined json-tool.sh). Without any
# engine, a pre-cleaned settings file supplied at build time (model-cleaned
# and validated) is applied; with neither, the uninstaller aborts before
# touching anything.
#
# Usage: build-managed-uninstaller.sh [style-name] [output-path] [precleaned-settings-file] [library-dir]
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=json-tool.sh
source "${SCRIPT_DIR}/json-tool.sh"

STYLE_NAME="${1:-Writing Style}"
OUTPUT="${2:-${HOME}/uninstall_claude_writing_style.sh}"
PRECLEANED="${3:-}"
LIBRARY="${4:-${HOME}/.claude/edgar-style-policies}"
SLUG=$(printf '%s' "$STYLE_NAME" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9' '-' | sed 's/^-//;s/-$//')
[[ -n "$SLUG" ]] || SLUG="writing-style"
if [[ -n "$PRECLEANED" ]]; then
    grep -qF "__CS_PRECLEANED_EOF__" "$PRECLEANED" && { echo "Pre-cleaned file contains the sentinel; aborting." >&2; exit 1; }
    EXISTING="$(cat "$PRECLEANED")" json_transform validate >/dev/null || {
        echo "Pre-cleaned settings file is not valid JSON: $PRECLEANED" >&2; exit 1; }
fi
OURS_SHAS=""
for c in "${LIBRARY}"/*/canonical*; do
    [[ -f "$c" ]] && OURS_SHAS+="$(norm_sha256 "$c") "
done

{
    cat <<'HDR'
#!/bin/bash
# Self-contained managed-tier uninstaller for a Claude writing-style policy.
# Generated by claude-style-toolkit. Run once, then it deletes itself:
#     sudo ~/uninstall_claude_writing_style.sh
# Removes only the policy's own files and keys; other managed settings stay.
set -euo pipefail
if [[ $EUID -ne 0 ]]; then echo "Run with sudo: sudo \"$0\"" >&2; exit 1; fi
TARGET_USER="${SUDO_USER:?Run via sudo from your normal account, not a root shell}"

# --- inlined json-tool.sh (engine dispatch: python3 / osascript / node) ---
HDR
    cat "${SCRIPT_DIR}/json-tool.sh"
    printf -- '# --- end json-tool.sh ---\n'
    printf 'STYLE_NAME=%q\nSLUG=%q\nOURS_SHAS=%q\n' "$STYLE_NAME" "$SLUG" "$OURS_SHAS"
    if [[ -n "$PRECLEANED" ]]; then
        printf 'PRECLEANED=$(cat <<'\''__CS_PRECLEANED_EOF__'\''\n'
        cat "$PRECLEANED"
        printf '\n__CS_PRECLEANED_EOF__\n)\n'
    else
        printf 'PRECLEANED=""\n'
    fi
    cat <<'BODY'
case "$(uname -s)" in
    Darwin) MANAGED_DIR="/Library/Application Support/ClaudeCode" ;;
    Linux)  MANAGED_DIR="/etc/claude-code" ;;
    *) echo "Unsupported OS: $(uname -s)" >&2; exit 1 ;;
esac
HOOKS_DIR="${MANAGED_DIR}/hooks"
STYLE_DIR="${MANAGED_DIR}/.claude/output-styles"
CM="${MANAGED_DIR}/CLAUDE.md"
SIDECAR="${MANAGED_DIR}/.edgar-style-policy"
STAMP="$(date +%Y%m%d%H%M%S).$$"
TOOLKIT_STYLES="$(toolkit_style_names "$STYLE_DIR")"
# For an install that predates the sidecar record: the toolkit's other files
# or settings entries mark the managed CLAUDE.md as its own. Read before the
# surgery below removes them.
LEGACY_OURS=0
if [[ ! -f "$SIDECAR" ]]; then
    if [[ -f "${HOOKS_DIR}/style-digest.sh" || -n "$TOOLKIT_STYLES" ]]; then LEGACY_OURS=1; fi
    if [[ -f "${MANAGED_DIR}/managed-settings.json" ]] && \
       command -p grep -qE 'writing-style-policy|style-digest\.sh|style-emoji-check\.sh' "${MANAGED_DIR}/managed-settings.json"; then LEGACY_OURS=1; fi
fi

ENGINE="$(detect_json_engine)"
if [[ -z "$ENGINE" && -z "$PRECLEANED" ]]; then
    echo "No JSON engine found (python3, osascript, or node) for the settings cleanup," >&2
    echo "and no pre-cleaned settings were supplied at build time." >&2
    echo "On macOS: xcode-select --install, then rerun. Nothing has been changed." >&2
    exit 1
fi

# Clear the macOS immutable flag if the user hardened files manually.
if [[ "$(uname -s)" == "Darwin" ]]; then
    chflags -R noschg "$MANAGED_DIR" 2>/dev/null || true
fi

# Settings surgery FIRST: strip only our keys, preserving anything else.
MS="${MANAGED_DIR}/managed-settings.json"
if [[ -f "$MS" ]]; then
    CLEANED=""
    if [[ -n "$ENGINE" ]]; then
        EXISTING="$(cat "$MS")"
        CLEANED="$(STYLE="$STYLE_NAME" EXISTING="$EXISTING" TOOLKIT_STYLES="$TOOLKIT_STYLES" \
            json_transform strip)" || CLEANED=""
    fi
    if [[ -z "$CLEANED" && -n "$PRECLEANED" ]]; then
        CLEANED="$PRECLEANED"
        echo "Applying pre-cleaned managed settings (model-cleaned at build time)."
    fi
    if [[ -z "$CLEANED" ]]; then
        echo "Could not clean managed-settings.json (unparseable and no pre-cleaned fallback)." >&2
        echo "Nothing has been changed." >&2
        exit 1
    fi
    cp "$MS" "${MS}.bak.${STAMP}"
    if [[ "$(printf '%s' "$CLEANED" | tr -d '[:space:]')" == "{}" ]]; then
        # The file was ours alone: remove it and this run's backup, so an
        # empty directory can actually be removed below.
        rm -f "$MS" "${MS}.bak.${STAMP}"
    else
        printf '%s\n' "$CLEANED" > "$MS"
    fi
fi

# The managed CLAUDE.md: removed only if it is the toolkit's own.
if [[ -f "$CM" ]]; then
    H="$(norm_sha256 "$CM")"
    OURS=0
    if [[ -f "$SIDECAR" ]] && command -p grep -qx "sha256=${H}" "$SIDECAR"; then OURS=1; fi
    for k in $OURS_SHAS; do if [[ "$k" == "$H" ]]; then OURS=1; fi; done
    if [[ $OURS -eq 0 && $LEGACY_OURS -eq 1 ]]; then OURS=1; fi
    if [[ $OURS -eq 1 ]]; then
        rm -f "$CM"
    else
        echo "Left ${CM} in place: it matches neither the toolkit's record nor any style in the library."
    fi
fi
if [[ -f "${CM}.pre-edgar-style-policy" && ! -e "$CM" ]]; then
    mv "${CM}.pre-edgar-style-policy" "$CM"
    echo "Restored the managed CLAUDE.md that was there before the toolkit's install."
fi

# Now the other files.
toolkit_style_files "$STYLE_DIR" | while IFS= read -r f; do rm -f "$f"; done
rm -f "${HOOKS_DIR}/style-digest.sh" \
      "${HOOKS_DIR}/style-emoji-check.sh" \
      "${HOOKS_DIR}/style-json-tool.sh" \
      "$SIDECAR"

# Remove now-empty policy directories; leave the managed dir in place if it
# still holds anything (other managed settings, older backups).
rmdir "$STYLE_DIR" "${MANAGED_DIR}/.claude" "$HOOKS_DIR" 2>/dev/null || true
if rmdir "$MANAGED_DIR" 2>/dev/null; then
    echo "Removed managed policy directory: ${MANAGED_DIR}"
else
    echo "Left ${MANAGED_DIR} in place (it still contains other files)."
fi

echo "Uninstalled managed-tier policy for style: ${STYLE_NAME}"
echo "The style library is untouched; reinstall or switch back at any time."
echo "Fully quit and restart Claude Code; the style is no longer applied."

SELF="$0"
rm -f "$SELF" && echo "Removed uninstaller: $SELF"
BODY
} > "$OUTPUT"
chmod 0755 "$OUTPUT"

echo "Wrote self-contained uninstaller: $OUTPUT"
echo "Have the user run, in a terminal:  sudo \"$OUTPUT\""
echo "It removes the policy and deletes itself on success."
