#!/bin/bash
# SPDX-FileCopyrightText: 2026 Gary Frattarola
# SPDX-License-Identifier: MIT OR Apache-2.0
#
# Assembles a self-contained managed-tier uninstaller and writes it to the
# user's home directory as uninstall_claude_writing_style.sh. The harness
# cannot elevate, so the user runs it: sudo ~/uninstall_claude_writing_style.sh
# The emitted uninstaller performs the settings surgery FIRST (removing only
# our keys: the digest hook by filename, the review hook by its
# "[writing-style-policy]" marker, and outputStyle if it names our style),
# then removes our files, then removes the managed directory only if empty,
# and deletes itself. python3 is required for the surgery; without it the
# uninstaller aborts before touching anything.
#
# Usage: build-managed-uninstaller.sh [style-name] [output-path]
set -euo pipefail

STYLE_NAME="${1:-Writing Style}"
OUTPUT="${2:-${HOME}/uninstall_claude_writing_style.sh}"
SLUG=$(printf '%s' "$STYLE_NAME" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9' '-' | sed 's/^-//;s/-$//')
[[ -n "$SLUG" ]] || SLUG="writing-style"

{
    cat <<'HDR'
#!/bin/bash
# Self-contained managed-tier uninstaller for a Claude writing-style policy.
# Generated by claude-style-toolkit. Run once, then it deletes itself:
#     sudo ~/uninstall_claude_writing_style.sh
# Removes only the policy's own files and keys; other managed settings stay.
set -euo pipefail
if [[ $EUID -ne 0 ]]; then echo "Run with sudo: sudo \"$0\"" >&2; exit 1; fi
TARGET_USER="${SUDO_USER:?Run via sudo from your normal account, not a root shell}"
HDR
    printf 'STYLE_NAME=%q\nSLUG=%q\n' "$STYLE_NAME" "$SLUG"
    cat <<'BODY'
case "$(uname -s)" in
    Darwin) MANAGED_DIR="/Library/Application Support/ClaudeCode"
            USER_HOME=$(dscl . -read "/Users/${TARGET_USER}" NFSHomeDirectory | sed 's/^[^:]*: //') ;;
    Linux)  MANAGED_DIR="/etc/claude-code"
            USER_HOME=$(getent passwd "$TARGET_USER" | cut -d: -f6) ;;
    *) echo "Unsupported OS: $(uname -s)" >&2; exit 1 ;;
esac
HOOKS_DIR="${MANAGED_DIR}/hooks"
STYLE_DIR="${MANAGED_DIR}/.claude/output-styles"
STAMP=$(date +%Y%m%d%H%M%S)

python3 -c 'import json' >/dev/null 2>&1 || {
    echo "python3 is required for the settings cleanup (on macOS: xcode-select --install)." >&2
    echo "Nothing has been changed." >&2
    exit 1
}

# Clear the macOS immutable flag if the user hardened files manually.
if [[ "$(uname -s)" == "Darwin" ]]; then
    chflags -R noschg "$MANAGED_DIR" 2>/dev/null || true
fi

# Settings surgery FIRST: strip only our keys, preserving anything else.
MS="${MANAGED_DIR}/managed-settings.json"
OURS_ONLY=0
if [[ -f "$MS" ]]; then
    cp "$MS" "${MS}.bak.${STAMP}"
    python3 - "$MS" "$STYLE_NAME" <<'PY'
import json, sys
path, style = sys.argv[1], sys.argv[2]
MARKER = "[writing-style-policy]"
with open(path, encoding="utf-8") as f:
    d = json.load(f)
if d.get("outputStyle") == style:
    d.pop("outputStyle", None)
hooks = d.get("hooks", {})
for ev in ("UserPromptSubmit", "Stop"):
    kept = []
    for g in hooks.get(ev, []):
        hs = [h for h in g.get("hooks", [])
              if "style-digest.sh" not in (h.get("command") or "")
              and not (h.get("type") == "prompt"
                       and str(h.get("prompt", "")).startswith(MARKER))]
        if hs:
            kept.append({**g, "hooks": hs})
    if kept:
        hooks[ev] = kept
    else:
        hooks.pop(ev, None)
if hooks:
    d["hooks"] = hooks
else:
    d.pop("hooks", None)
with open(path, "w", encoding="utf-8") as f:
    json.dump(d, f, indent=2)
    f.write("\n")
PY
    # If nothing but empty braces remain, the file was ours alone: remove it
    # and this run's backup, so an empty directory can actually be removed.
    if [[ "$(tr -d '[:space:]' < "$MS")" == "{}" ]]; then
        rm -f "$MS" "${MS}.bak.${STAMP}"
        OURS_ONLY=1
    fi
fi

# Now the files.
rm -f "${MANAGED_DIR}/CLAUDE.md" \
      "${HOOKS_DIR}/style-digest.sh" \
      "${STYLE_DIR}/${SLUG}.md"

# Remove now-empty policy directories; leave the managed dir in place if it
# still holds anything (other managed settings, older backups).
rmdir "$STYLE_DIR" "${MANAGED_DIR}/.claude" "$HOOKS_DIR" 2>/dev/null || true
if rmdir "$MANAGED_DIR" 2>/dev/null; then
    echo "Removed managed policy directory: ${MANAGED_DIR}"
else
    echo "Left ${MANAGED_DIR} in place (it still contains other files)."
fi

echo "Uninstalled managed-tier policy for style: ${STYLE_NAME}"
echo "The canonical directive in your repo is untouched; reinstall anytime."
echo "Fully quit and restart Claude Code; the style is no longer applied."

SELF="$0"
rm -f "$SELF" && echo "Removed uninstaller: $SELF"
BODY
} > "$OUTPUT"
chmod 0755 "$OUTPUT"

echo "Wrote self-contained uninstaller: $OUTPUT"
echo "Have the user run, in a terminal:  sudo \"$OUTPUT\""
echo "It removes the policy and deletes itself on success."
