#!/bin/bash
# SPDX-FileCopyrightText: 2026 Gary Frattarola
# SPDX-License-Identifier: MIT OR Apache-2.0
#
# Assembles a single, self-contained managed-tier installer and writes it to
# the user's home directory as install_claude_writing_style.sh. The directive,
# digest hook, settings fragment (outputStyle + digest command hook + the
# judgment-review prompt hook), and the JSON engine library are embedded
# inline — human-readable, so the sudo script can be inspected before running.
# The emitted installer writes root-owned policy files to the OS managed
# directory and deletes itself.
#
# Settings handling in the emitted installer, in order of preference:
#   1. Any JSON engine on the target machine (python3, osascript on macOS,
#      or node — identical on both OSes, via the inlined json-tool.sh) ->
#      our fragment is MERGED into any existing managed-settings.json
#      (other managed settings preserved; our marker-tagged review hook
#      replaced on re-install).
#   2. No engine, but a pre-merged settings file was supplied at build time
#      (the guiding model reads the world-readable managed-settings.json,
#      merges our fragment itself, and validates the result) -> the emitted
#      installer writes that pre-merged content (backup first).
#   3. Neither -> backup and replace with the bare fragment, and say so.
#
# Usage: build-managed-installer.sh <staging-dir> [style-name] [output-path] [premerged-settings-file]
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=json-tool.sh
source "${SCRIPT_DIR}/json-tool.sh"

STAGING="${1:?Usage: build-managed-installer.sh <staging-dir> [style-name] [output-path] [premerged-settings-file]}"
STYLE_NAME="${2:-Writing Style}"
OUTPUT="${3:-${HOME}/install_claude_writing_style.sh}"
PREMERGED="${4:-}"
case "$STYLE_NAME" in
    *$'\n'*) echo "Style name must not contain newlines." >&2; exit 1 ;;
    \"*)     echo "Style name must not start with a quote." >&2; exit 1 ;;
esac
SLUG=$(printf '%s' "$STYLE_NAME" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9' '-' | sed 's/^-//;s/-$//')
[[ -n "$SLUG" ]] || SLUG="writing-style"

for f in canonical.md digest.sh review-prompt.txt; do
    [[ -f "${STAGING}/${f}" ]] || { echo "Missing ${STAGING}/${f}" >&2; exit 1; }
done
[[ -n "$(detect_json_engine)" ]] || {
    echo "This builder needs a JSON engine (python3, osascript, or node)." >&2
    exit 1
}

# Collision guard: payloads must not contain the heredoc sentinels wrapping them.
guard() { grep -qF "$2" "$1" && { echo "Payload $1 contains sentinel $2; aborting." >&2; exit 1; } || true; }
GUARDED_FILES=("${STAGING}/canonical.md" "${STAGING}/digest.sh" "${STAGING}/review-prompt.txt")
[[ -n "$PREMERGED" ]] && GUARDED_FILES+=("$PREMERGED")
for s in __CS_DIRECTIVE_EOF__ __CS_STYLE_EOF__ __CS_DIGEST_EOF__ __CS_FRAG_EOF__ __CS_PREMERGED_EOF__; do
    for f in "${GUARDED_FILES[@]}"; do guard "$f" "$s"; done
done
if [[ -n "$PREMERGED" ]]; then
    EXISTING="$(cat "$PREMERGED")" json_transform validate >/dev/null || {
        echo "Pre-merged settings file is not valid JSON: $PREMERGED" >&2; exit 1; }
fi

# Build the settings fragment at build time (engine-agnostic): valid JSON with
# the review prompt safely encoded; the hooks path is a placeholder
# substituted per-OS at run time.
FRAGMENT="$(STYLE="$STYLE_NAME" PROMPT="$(cat "${STAGING}/review-prompt.txt")" json_transform fragment)"

{
    cat <<'HDR'
#!/bin/bash
# Self-contained managed-tier installer for a Claude writing-style policy.
# Generated by claude-style-toolkit. Run once, then it deletes itself:
#     sudo ~/install_claude_writing_style.sh
# Root-owned policy is written to the OS managed directory. Safe to read first.
set -euo pipefail
if [[ $EUID -ne 0 ]]; then echo "Run with sudo: sudo \"$0\"" >&2; exit 1; fi
TARGET_USER="${SUDO_USER:?Run via sudo from your normal account, not a root shell}"

# --- inlined json-tool.sh (engine dispatch: python3 / osascript / node) ---
HDR
    cat "${SCRIPT_DIR}/json-tool.sh"
    printf -- '# --- end json-tool.sh ---\n'
    printf 'STYLE_NAME=%q\nSLUG=%q\n' "$STYLE_NAME" "$SLUG"
    cat <<'BODY1'
case "$(uname -s)" in
    Darwin) MANAGED_DIR="/Library/Application Support/ClaudeCode"; GROUP="wheel"
            USER_HOME=$(dscl . -read "/Users/${TARGET_USER}" NFSHomeDirectory | sed 's/^[^:]*: //') ;;
    Linux)  MANAGED_DIR="/etc/claude-code"; GROUP="root"
            USER_HOME=$(getent passwd "$TARGET_USER" | cut -d: -f6) ;;
    *) echo "Unsupported OS: $(uname -s)" >&2; exit 1 ;;
esac
HOOKS_DIR="${MANAGED_DIR}/hooks"
STYLE_DIR="${MANAGED_DIR}/.claude/output-styles"
mkdir -p "$HOOKS_DIR" "$STYLE_DIR"
BODY1
    # Managed CLAUDE.md (directive verbatim).
    printf 'cat > "${MANAGED_DIR}/CLAUDE.md" <<'\''__CS_DIRECTIVE_EOF__'\''\n'
    cat "${STAGING}/canonical.md"
    printf '\n__CS_DIRECTIVE_EOF__\n'
    # Output style: frontmatter + directive body.
    printf 'cat > "${STYLE_DIR}/${SLUG}.md" <<'\''__CS_STYLE_EOF__'\''\n'
    printf -- '---\nname: %s\ndescription: Writing style directive (managed; do not edit)\n---\n\n' "$STYLE_NAME"
    cat "${STAGING}/canonical.md"
    printf '\n__CS_STYLE_EOF__\n'
    # Digest hook.
    printf 'cat > "${HOOKS_DIR}/style-digest.sh" <<'\''__CS_DIGEST_EOF__'\''\n'
    cat "${STAGING}/digest.sh"
    printf '\n__CS_DIGEST_EOF__\n'
    # Settings fragment (built and validated at build time).
    printf 'FRAGMENT=$(cat <<'\''__CS_FRAG_EOF__'\''\n'
    printf '%s\n' "$FRAGMENT"
    printf '__CS_FRAG_EOF__\n)\n'
    # Optional pre-merged settings (model-merged at build time, validated).
    if [[ -n "$PREMERGED" ]]; then
        printf 'PREMERGED=$(cat <<'\''__CS_PREMERGED_EOF__'\''\n'
        cat "$PREMERGED"
        printf '\n__CS_PREMERGED_EOF__\n)\n'
    else
        printf 'PREMERGED=""\n'
    fi
    cat <<'BODY2'
chmod 0755 "${HOOKS_DIR}/style-digest.sh"
FRAGMENT="${FRAGMENT//__CS_HOOKS_DIR__/${HOOKS_DIR}}"
[[ -n "$PREMERGED" ]] && PREMERGED="${PREMERGED//__CS_HOOKS_DIR__/${HOOKS_DIR}}"

MS="${MANAGED_DIR}/managed-settings.json"
ENGINE="$(detect_json_engine)"
EXISTING=""
[[ -f "$MS" ]] && EXISTING="$(cat "$MS")"
if [[ -n "$ENGINE" ]] && MERGED="$(FRAGMENT="$FRAGMENT" EXISTING="$EXISTING" json_transform merge)"; then
    # Merge path: preserve any other managed settings; replace our own
    # marker-tagged review hook and digest entry so re-installs update them.
    [[ -f "$MS" ]] && cp "$MS" "${MS}.bak.$(date +%Y%m%d%H%M%S)"
    printf '%s\n' "$MERGED" > "$MS"
    echo "Merged policy into managed-settings.json (engine: ${ENGINE}; other managed settings preserved)."
elif [[ -n "$PREMERGED" ]]; then
    # No engine (or unparseable existing file): use the model's build-time merge.
    [[ -f "$MS" ]] && cp "$MS" "${MS}.bak.$(date +%Y%m%d%H%M%S)"
    printf '%s\n' "$PREMERGED" > "$MS"
    echo "Wrote pre-merged managed-settings.json (model-merged at build time; backup kept)."
else
    # Last resort: back up any existing file and write our fragment whole.
    if [[ -f "$MS" ]]; then
        cp "$MS" "${MS}.bak.$(date +%Y%m%d%H%M%S)"
        echo "No JSON engine available and no pre-merged settings supplied:"
        echo "backed up existing managed-settings.json and replaced it."
    fi
    printf '%s\n' "$FRAGMENT" > "$MS"
fi

# Root-own the whole tree, then set file modes.
chown -R "root:${GROUP}" "$MANAGED_DIR"
chmod 0644 "${MANAGED_DIR}/CLAUDE.md" "$MS" "${STYLE_DIR}/${SLUG}.md"

echo "Installed (managed tier) to ${MANAGED_DIR} for style: ${STYLE_NAME}"
echo "Fully quit and restart Claude Code (a /clear is not enough), then verify:"
echo "  1. Ask Claude whether a managed CLAUDE.md and the '${STYLE_NAME}'"
echo "     output style are active (it can confirm both from its context)."
echo "  2. Confirm the digest line arrives with each prompt."
echo "  3. The review hook was sandbox-tested before install; in live use it"
echo "     revises replies that break the rules."

SELF="$0"
rm -f "$SELF" && echo "Removed installer: $SELF"
BODY2
} > "$OUTPUT"
chmod 0755 "$OUTPUT"

echo "Wrote self-contained installer: $OUTPUT"
echo "Have the user run, in a terminal:  sudo \"$OUTPUT\""
echo "It writes the policy root-owned and deletes itself on success."
